"""
Build assets.

1. Copy song in assets/ to ./dist (and potentially compress it)
2. Copy PNGs in assets/ to ./dist
3. Generate the .hpp file from chart.json.
4. Create index/shorthands for the sprites to automate it a bit
"""

from shutil import copy
import os
from glob import glob
import json

# Change dir
os.chdir(os.path.dirname(os.path.abspath(__file__)))

# ================== COPY ================== #

def copy_files_to_dist():
    """
    Copy the PNG and OPUS
    """
    for filename in glob("./assets/*"):
        if os.path.splitext(filename)[1] in [".png", ".opus"]:
            copy(filename, os.path.join("./dist", os.path.basename(filename)))

# ================= BUILD ================== #

CHART_HPP_TEMPLATE = """\
// Chart.
// This file is generated by build_assets.py

#include <vector>
#include <string.h>
#include <unordered_map>

namespace Chart {{
// Song BPM
const float SONG_BPM = {};
// Song title/filename (likely unused)
const std::string SONG_TITLE = "{}";
// Song number of rounds, inferred from chart
const size_t SONG_NUM_ROUNDS = {};

// The Chart
std::vector<std::vector<float>> chart_beats = {}

// Word list
std::vector<std::vector<std::string>> chart_words = {}

// Sprite helper
std::unordered_map<std::string, std::string> mesh_name_to_sprite = {}

std::unordered_map<std::string, size_t> mesh_name_to_width = {}

}}
// FILE END
"""

def build_chart():
    """
    Build Chart.hpp from chart.json
    """
    with open("assets/chart.json", 'r') as f:
        chart_obj = json.load(f)

    try:
        song_bpm = chart_obj["bpm"]
        song_title = chart_obj["track"]

        beat_lines = []
        word_lines = []
        for i, sentence in enumerate(chart_obj["chart"]):
            beats = sentence["beats"]
            line = '\t{' + ', '.join([str(beat) for beat in beats]) + '},'
            beat_lines.append(line)
            wordlist = sentence["words"]
            words = '\t{' + ', '.join(['"' + str(w) + '"' for w in wordlist]) + '},'
            word_lines.append(words)
        
        num_rounds = len(chart_obj["chart"])

        # Sprites
        with open("./assets/sprites.json", 'r') as f:
            sprites_obj = json.load(f)

        sprite_names = ['\t{"' + key + '", "' + value[0] + '"},' for key, value in sprites_obj.items()]
        sprite_width = ['\t{"' + key + '", ' + str(value[1]) + '},' for key, value in sprites_obj.items()]


        hpp_text = CHART_HPP_TEMPLATE.format(
            song_bpm,
            song_title,
            num_rounds,
            '{\n' + '\n'.join(beat_lines) + '\n};',
            '{\n' + '\n'.join(word_lines) + '\n};',
            '{\n' + '\n'.join(sprite_names) + '\n};',
            '{\n' + '\n'.join(sprite_width) + '\n};',
        )
        with open("Chart.hpp", 'w') as f:
            f.write(hpp_text)

    except Exception as e:
        # Likely KeyError
        raise e



if __name__ == "__main__":
    copy_files_to_dist()

    build_chart()
