// Chart.
// This file is generated by build_assets.py

#include <vector>
#include <string.h>
#include <unordered_map>

namespace Chart {
// Song BPM
const float SONG_BPM = 120;
// Song title/filename (likely unused)
const std::string SONG_TITLE = "song.mp3";
// Song number of rounds, inferred from chart
const size_t SONG_NUM_ROUNDS = 12;

// The Chart
std::vector<std::vector<float>> chart_beats = {
	{},
	{0.0, 4.0},
	{0.0, 2.0, 4.0},
	{0.0, 2.0, 4.0},
	{0.0, 2.0, 3.0, 4.0},
	{0.0, 2.0, 3.0, 4.0, 6.0},
	{0.0, 1.5, 3.0, 5.5, 6.0, 7.0},
	{0.0, 1.0, 3.0, 4.0, 5.0, 5.5},
	{0.0, 1.5, 2.0, 3.5, 4.0, 5.0, 7.0},
	{0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 6.0, 7.0},
	{0.0, 0.75, 1.5, 2.0, 3.0, 4.0, 4.75, 5.5, 6.25, 7.0, 7.5},
	{0.0, 0.5, 0.75, 1.25, 2.0, 2.5, 2.75, 3.25, 4.0, 4.5, 4.75, 5.25, 6.0, 7.0},
};

// Word list
std::vector<std::vector<std::string>> chart_words = {
	{},
	{"ok"},
	{"cat", "bee", "cow", "dog", "fox"},
	{"pea", "nut", "ham", "jam", "oat", "egg"},
	{"java", "rust", "bash", "ruby"},
	{"magic", "lyric", "hymns", "spell", "curse", "torch", "light", "music", "dream", "fable"},
	{"defend", "attack", "pocket", "escape", "accept", "cancel"},
	{"rapper", "bemani", "rhythm", "heaven", "doctor", "maimai", "deluxe", "guitar", "master", "garupa", "arcaea"},
	{"trumpet", "cymbals", "cowbell", "bagpipe", "bassoon", "bombard", "cornett", "ocarina", "marimba"},
	{"obliterate", "regenerate", "popularize", "translator", "identifier", "encryption", "crystalize", "bottleneck"},
	{"spectacular", "calibration", "exaggerated", "fluctuation", "subroutines"},
	{"triangularized", "backpropagated", "abstractedness", "cardiovascular", "capitalisation", "fathomlessness"},
};

// Sprite helper
std::unordered_map<std::string, std::string> mesh_name_to_sprite = {
	{"Player", "Player.png"},
	{"Enemy", "Slime.png"},
	{"Plane", "circle.png"},
	{"Effect", "lightning.png"},
};

std::unordered_map<std::string, size_t> mesh_name_to_width = {
	{"Player", 256},
	{"Enemy", 256},
	{"Plane", 64},
	{"Effect", 256},
};

}
// FILE END
